# Generated by Django 2.1.2 on 2018-10-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=144)),
                ('username', models.CharField(max_length=144)),
                ('password', models.CharField(max_length=144)),
                ('state', models.CharField(choices=[(0, 'generated'), (1, 'paid'), (2, 'created'), (3, 'expired')], max_length=2)),
            ],
        ),
    ]
